#!/usr/bin/env bash
set -euo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)

if find "$repo_root" -type l -print -quit | grep -q .; then
    printf 'Symbolic links are not permitted.\n' >&2
    exit 1
fi

if find "$repo_root" -type f -size +5M -print -quit | grep -q .; then
    printf 'Repository files must not exceed 5 MiB.\n' >&2
    exit 1
fi

authorship_pattern='(chat''gpt|open''ai|clau''de|co''pilot|generated by a''i|doglio-''production|2\.29\.11\.5''6|BEGIN (RSA |OPENSSH )?PRIVATE KEY)'

if rg -n -i --hidden \
    --glob '!.git/**' \
    --glob '!tests/repository-hygiene.test.sh' \
    "$authorship_pattern" \
    "$repo_root"; then
    printf 'Forbidden private, credential, or authorship text found.\n' >&2
    exit 1
fi

if rg -n --hidden --glob '!.git/**' \
    '(rpcpassword|RPC_PASSWORD|RPC_CREDENTIALS)=[^$<{[:space:]][^[:space:]]*' \
    "$repo_root"; then
    printf 'A committed RPC credential value was found.\n' >&2
    exit 1
fi

printf 'Repository hygiene checks passed.\n'
